version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    working_dir: /app
    command: ["npm", "start"]
    volumes:
      - "./app:/app"
