version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["npm", "test"]
    volumes:
      - ".env.example:/app/.env"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    restart: always
