name: run tests and deploy
on: push
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Run tests
        run: make test-prod
